version: '3'
services:
  mongodb:
    image: mongo
    container_name: webfluxmongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
